### PR TITLE
Migrate canvas layer to leaflet 1.x

### LINKED ISSUE #23: Migrate to leaflet 1.x

### PR DESCRIPTION
**Pull request by donflopez**
To sync with https://github.com/CartoDB/torque/pull/284 and fix #23

### CODE REVIEW

**Comment by rochoa** [comment]
What is the acceptance criteria for this one?

**Comment by donflopez** [comment]
## Acceptance Criteria

- Open example.html file
- Check that the circle animation is working over leaflet 1.0.x

**Comment by donflopez** [comment]
This changes fix https://github.com/CartoDB/cartodb/issues/11804

**Comment by Frazer** [comment]
in example.html - when zooming I get a large distortion artifact, while the zoom is happening the center of the BigPointLayer seems to jump to a random position, then back to the desired position when the zoom finishes.

**Review by metroyanno — APPROVED** [review]

**Comment by jopfre** [comment]
I believe line 123 `bg.style[transform] =  L.DomUtil.getTranslateString(origin) + ' scale(' + e.scale + ') ';` should now be `L.DomUtil.setTransform(bg, origin, e.scale);` as Leaflet 1.3.4 says `Uncaught TypeError: L.DomUtil.getTranslateString is not a function`.

**Pull request closed without merging**
