### PR TITLE
Resize Fix

### PR DESCRIPTION
**Pull request by mikegiddens**
This fixes the redraw issue when the browser is resized.

### CODE REVIEW

**Comment by javisantana** [comment]
@fdansv could you review? 

thanks @mikegiddens

**Comment by mikegiddens** [comment]
@javisantana This is actually your code from Torque and just copied it over so it would work on this lib too and make it easy to merge.

**Comment by javisantana** [comment]
haha, lovely

**Comment by andrewxhill** [comment]
@fdansv could you still review?

:D

**Comment by fdansv** [comment]
Looks good to me, but I don't have write access for some reason ;)

Thanks @mikegiddens!

**Comment by javisantana** [comment]
haha

**Pull request merged**
